language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t abhinavraj/docker-react-f Dockerfile.dev .

script:
  - docker run -e CI=true abhinavraj/docker-react npm run test
